# Generated by Django 3.1.5 on 2021-04-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseFullCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=300, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Category',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='UseFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Web Site Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='usefull-images/', verbose_name='Site Logo')),
                ('link', models.URLField(verbose_name='Site URL')),
                ('free', models.BooleanField(default=False, verbose_name='Free')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usefull_category', to='core.usefullcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Use Full',
            },
        ),
    ]
