# Generated by Django 3.1.5 on 2021-01-26 05:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.CharField(max_length=300, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category-image/%d/%m/%Y/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='product-image/%d/%m/%Y/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='file',
            field=models.FileField(upload_to='mockup-file/%d/%m/%Y/', verbose_name='MockUp File'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_file', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='product.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Free'),
        ),
        migrations.AlterField(
            model_name='product',
            name='liked',
            field=models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='product_tags', to='product.Tag', verbose_name='Product Tags'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ManyToManyField(to='product.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='Tag Name'),
        ),
    ]
