# Generated by Django 3.1.5 on 2021-01-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210126_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category-image/%d/%m/%Y/', verbose_name='Image'),
        ),
    ]
