# Generated by Django 3.1.5 on 2021-01-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210126_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('mockup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='product.product', verbose_name='Product')),
            ],
        ),
    ]
