# Generated by Django 3.1.5 on 2021-02-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_userviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewed',
        ),
    ]
