# Generated by Django 3.1.5 on 2021-02-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockup',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
